### ISSUE TITLE
Fix the read me

### ISSUE THREAD

**Issue by laxuscullen** [Ashutosh1104/AnimeNamesAPI#1]
Your own examples return error like "write full name" when opened lol

**Comment by Ashutosh1104** [comment]
Yeah I know the website I was scrapping changed stuff on their end and I
have to fix it but I just don't have the time I will private this for now
thanks for reminding me.

**Comment by laxuscullen** [comment]
Just a small question, what kind of image is returned? Is it like a thumbnail from anime planet?

**Comment by Ashutosh1104** [comment]
It's from this website
https://www.anime-planet.com/

I plan to integrate MAL into this in future but scrapping MAL will require
a database to store links as it has unique ids attached to each anime page
url.... while anime planet URL are just names of anime .

So if you want to scrap mal it's going to need more work I think I have
used db in this too but it's not really required it was just for learning
purposes after I made it without any db help
